version: '3.7'
services:

  thai-pbs-e-meeting-api-service:
    image: php:shiping
    build:
      context: C:/Users/Nawawit.P/Documents/GitHub/Restructure-Thai-PBS-API/api
      dockerfile: Dockerfile
    restart: always
    container_name: final_project
    volumes:
      - C:/Users/Nont/OneDrive/Desktop/Final_project/api:/var/www/html
    ports:
      - 3003:80
    environment:
      - TZ=Asia/Bangkok
